Repository proto-graphql/proto-graphql-js, pull requests merged in 2023-10, with the labels that each got.

#283 ci: refactor workflows
  .github/actions/setup-node/action.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
Labels: build :building_construction:

#282 Bump pnpm to v8.8.0 and turbo to 1.10.15
  package.json
  pnpm-lock.yaml
Labels: build :building_construction:

#285 Bump typescript, eslint, prettier
  devPackages/eslint-config/index.js
  devPackages/eslint-config/package.json
  package.json
  packages/@proto-graphql/codegen-core/src/printer/graphqlExtensions.ts
  packages/@proto-graphql/codegen-core/src/printer/options.ts
  packages/@proto-graphql/codegen-core/src/printer/util.ts
  packages/@proto-graphql/codegen-core/src/types/FieldBase.ts
  packages/@proto-graphql/codegen-core/src/types/InputObjectField.ts
  packages/@proto-graphql/codegen-core/src/types/InputObjectType.ts
  packages/@proto-graphql/codegen-core/src/types/ObjectField.ts
  packages/@proto-graphql/codegen-core/src/types/TypeBase.ts
  packages/@proto-graphql/codegen-core/src/types/options.ts
  packages/@proto-graphql/codegen-core/src/types/types.ts
  packages/@proto-graphql/codegen-core/src/types/util.ts
  packages/@proto-graphql/proto-descriptors/src/common.ts
  packages/@proto-graphql/proto-descriptors/src/impls.ts
  packages/@proto-graphql/proto-descriptors/src/interfaces.ts
  packages/@proto-graphql/proto-descriptors/src/scalars.ts
  packages/@proto-graphql/protoc-plugin-helpers/src/parseParams.ts
  packages/@proto-nexus/proto-fields-plugin/src/plugin.ts
  packages/@proto-nexus/protobufjs/src/wrappers.ts
  packages/proto-nexus/src/Transformer.ts
  packages/proto-nexus/src/extensions.ts
  packages/protoc-gen-nexus/src/__tests__/__helpers__/process.test.helper.ts
  packages/protoc-gen-nexus/src/dslgen/printers/field.ts
  packages/protoc-gen-nexus/src/dslgen/printers/inputObjectType.ts
  packages/protoc-gen-nexus/src/dslgen/printers/objectType.ts
  packages/protoc-gen-pothos/src/__tests__/__helpers__/process.test.helper.ts
  packages/protoc-gen-pothos/src/dslgen/printers/enumType.ts
  packages/protoc-gen-pothos/src/dslgen/printers/fieldResolver/enumFieldResolver.ts
  packages/protoc-gen-pothos/src/dslgen/printers/inputObjectType.ts
  packages/protoc-gen-pothos/src/dslgen/printers/oneofUnionType.ts
  pnpm-lock.yaml
  scripts/setupE2ETests.ts
Labels: devDependencies

#274 Fix regression on skip_resolver
  .changeset/skip-resolver-fix.md
  packages/protoc-gen-nexus/src/__tests__/__snapshots__/process.test.ts.snap
  packages/protoc-gen-nexus/src/dslgen/printers/field.ts
Labels: bug :bug:

#286 chore: fix devDependencies
  devPackages/eslint-config/package.json
  devPackages/testapis-proto/package.json
  e2e/helper/package.json
  e2e/testapis/google-protobuf/package.json
  e2e/tests/nexus--deprecation--google-protobuf/package.json
  e2e/tests/nexus--deprecation--protobufjs/package.json
  e2e/tests/nexus--edgecases-import_from_same_pkg--google-protobuf/package.json
  e2e/tests/nexus--edgecases-import_from_same_pkg--protobufjs/package.json
  e2e/tests/nexus--edgecases-import_squashed_union--google-protobuf/package.json
  e2e/tests/nexus--edgecases-import_squashed_union--protobufjs/package.json
  e2e/tests/nexus--empty_types--google-protobuf/package.json
  e2e/tests/nexus--empty_types--protobufjs/package.json
  e2e/tests/nexus--enums--google-protobuf/package.json
  e2e/tests/nexus--enums--protobufjs/package.json
  e2e/tests/nexus--extensions--google-protobuf/package.json
  e2e/tests/nexus--extensions--protobufjs/package.json
  e2e/tests/nexus--field_behavior--google-protobuf/package.json
  e2e/tests/nexus--field_behavior--protobufjs/package.json
  e2e/tests/nexus--multipkgs--google-protobuf/package.json
  e2e/tests/nexus--multipkgs--protobufjs/package.json
  e2e/tests/nexus--nested--google-protobuf/package.json
  e2e/tests/nexus--nested--protobufjs/package.json
  e2e/tests/nexus--oneof--google-protobuf/package.json
  e2e/tests/nexus--oneof--protobufjs/package.json
  e2e/tests/nexus--primitives--google-protobuf/package.json
  e2e/tests/nexus--primitives--protobufjs/package.json
  e2e/tests/nexus--proto3_optional--google-protobuf/package.json
  e2e/tests/nexus--proto3_optional--protobufjs/package.json
  e2e/tests/nexus--wktypes--google-protobuf/package.json
  e2e/tests/nexus--wktypes--protobufjs/package.json
  e2e/tests/pothos--deprecation--ts-proto/package.json
  e2e/tests/pothos--edgecases-import_from_same_pkg--ts-proto/package.json
  e2e/tests/pothos--edgecases-import_squashed_union--ts-proto/package.json
  e2e/tests/pothos--empty_types--ts-proto/package.json
  e2e/tests/pothos--enums--ts-proto/package.json
  e2e/tests/pothos--extensions--ts-proto/package.json
  e2e/tests/pothos--field_behavior--ts-proto/package.json
  e2e/tests/pothos--multipkgs--ts-proto/package.json
  e2e/tests/pothos--nested--ts-proto/package.json
  e2e/tests/pothos--oneof--ts-proto/package.json
  e2e/tests/pothos--primitives--ts-proto-with-forcelong-number/package.json
  e2e/tests/pothos--primitives--ts-proto/package.json
  e2e/tests/pothos--proto3_optional--ts-proto/package.json
  e2e/tests/pothos--wktypes--ts-proto-with-forcelong-number/package.json
  e2e/tests/pothos--wktypes--ts-proto/package.json
  package.json
  packages/@proto-graphql/codegen-core/package.json
  packages/@proto-graphql/proto-descriptors/package.json
  packages/@proto-graphql/protoc-plugin-helpers/package.json
  packages/@proto-nexus/google-protobuf/package.json
  packages/@proto-nexus/proto-fields-plugin/package.json
  packages/@proto-nexus/protobufjs/package.json
  packages/proto-nexus/package.json
  packages/protoc-gen-nexus/package.json
  packages/protoc-gen-pothos/package.json
  pnpm-lock.yaml
  scripts/setupE2ETests.ts
  workspacePackageConfig.json
Labels: devDependencies

#289 chore: drop lint-staged and husky
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
Labels: devDependencies

#290 chore: add PROTO3_OPTIONAL to supported features
  .changeset/rare-wombats-double.md
  packages/@proto-graphql/protoc-plugin-helpers/src/process.ts
Labels: bug :bug:

#292 chore(deps): bump protobufjs to v7
  package.json
  pnpm-lock.yaml
Labels: devDependencies

#291 chore(deps): bump changesets monorepo
  package.json
  pnpm-lock.yaml
Labels: devDependencies

#293 fix: deprecated input fields are nullable
  e2e/tests/nexus--deprecation--google-protobuf/__generated__/schema.graphql
  e2e/tests/nexus--deprecation--protobufjs/__generated__/schema.graphql
  e2e/tests/pothos--deprecation--ts-proto/__generated__/schema.graphql
  packages/@proto-graphql/codegen-core/src/types/InputObjectField.ts
  packages/protoc-gen-nexus/src/__tests__/__snapshots__/process.test.ts.snap
  packages/protoc-gen-pothos/src/__tests__/__snapshots__/process.test.ts.snap
Labels: bug :bug:

#288 chore(deps): bump graphql to 16.8.1
  e2e/tests/nexus--deprecation--google-protobuf/__generated__/schema.graphql
  e2e/tests/nexus--deprecation--protobufjs/__generated__/schema.graphql
  e2e/tests/nexus--edgecases-import_from_same_pkg--google-protobuf/__generated__/schema.graphql
  e2e/tests/nexus--edgecases-import_from_same_pkg--protobufjs/__generated__/schema.graphql
  e2e/tests/nexus--edgecases-import_squashed_union--google-protobuf/__generated__/schema.graphql
  e2e/tests/nexus--edgecases-import_squashed_union--protobufjs/__generated__/schema.graphql
  e2e/tests/nexus--empty_types--google-protobuf/__generated__/schema.graphql
  e2e/tests/nexus--empty_types--protobufjs/__generated__/schema.graphql
  e2e/tests/nexus--enums--google-protobuf/__generated__/schema.graphql
  e2e/tests/nexus--enums--protobufjs/__generated__/schema.graphql
  e2e/tests/nexus--extensions--google-protobuf/__generated__/schema.graphql
  e2e/tests/nexus--extensions--protobufjs/__generated__/schema.graphql
  e2e/tests/nexus--field_behavior--google-protobuf/__generated__/schema.graphql
  e2e/tests/nexus--field_behavior--protobufjs/__generated__/schema.graphql
  e2e/tests/nexus--multipkgs--google-protobuf/__generated__/schema.graphql
  e2e/tests/nexus--multipkgs--protobufjs/__generated__/schema.graphql
  e2e/tests/nexus--nested--google-protobuf/__generated__/schema.graphql
  e2e/tests/nexus--nested--protobufjs/__generated__/schema.graphql
  e2e/tests/nexus--oneof--google-protobuf/__generated__/schema.graphql
  e2e/tests/nexus--oneof--protobufjs/__generated__/schema.graphql
  e2e/tests/nexus--primitives--google-protobuf/__generated__/schema.graphql
  e2e/tests/nexus--primitives--protobufjs/__generated__/schema.graphql
  e2e/tests/nexus--proto3_optional--google-protobuf/__generated__/schema.graphql
  e2e/tests/nexus--proto3_optional--protobufjs/__generated__/schema.graphql
  e2e/tests/nexus--wktypes--google-protobuf/__generated__/schema.graphql
  e2e/tests/nexus--wktypes--protobufjs/__generated__/schema.graphql
  e2e/tests/pothos--deprecation--ts-proto/__generated__/schema.graphql
  e2e/tests/pothos--edgecases-import_from_same_pkg--ts-proto/__generated__/schema.graphql
  e2e/tests/pothos--edgecases-import_squashed_union--ts-proto/__generated__/schema.graphql
  e2e/tests/pothos--empty_types--ts-proto/__generated__/schema.graphql
  e2e/tests/pothos--enums--ts-proto/__generated__/schema.graphql
  e2e/tests/pothos--extensions--ts-proto/__generated__/schema.graphql
  e2e/tests/pothos--field_behavior--ts-proto/__generated__/schema.graphql
  e2e/tests/pothos--multipkgs--ts-proto/__generated__/schema.graphql
  e2e/tests/pothos--nested--ts-proto/__generated__/schema.graphql
  e2e/tests/pothos--oneof--ts-proto/__generated__/schema.graphql
  e2e/tests/pothos--primitives--ts-proto-with-forcelong-number/__generated__/schema.graphql
  e2e/tests/pothos--primitives--ts-proto/__generated__/schema.graphql
  e2e/tests/pothos--proto3_optional--ts-proto/__generated__/schema.graphql
  e2e/tests/pothos--wktypes--ts-proto-with-forcelong-number/__generated__/schema.graphql
  e2e/tests/pothos--wktypes--ts-proto/__generated__/schema.graphql
  package.json
  pnpm-lock.yaml
Labels: devDependencies

#294 build: refer internal dependencies with `workspace:`
  .changeset/config.json
  .changeset/hip-buses-live.md
  packages/@proto-graphql/codegen-core/package.json
  packages/@proto-graphql/protoc-plugin-helpers/package.json
  packages/@proto-nexus/google-protobuf/package.json
  packages/@proto-nexus/protobufjs/package.json
  packages/protoc-gen-nexus/package.json
  packages/protoc-gen-pothos/package.json
  pnpm-lock.yaml
Labels: build :building_construction:

#295 fix(protoc-gen-pothos): fix required custom scalar type of input object field
  .changeset/proud-schools-notice.md
  package.json
  packages/@proto-graphql/codegen-core/src/types/ScalarType.ts
  packages/protoc-gen-pothos/src/__tests__/__snapshots__/process.test.ts.snap
  packages/protoc-gen-pothos/src/dslgen/printers/inputObjectType.ts
  pnpm-lock.yaml
Labels: bug :bug:

#297 build: generate code with buf instead of protoc
  .github/workflows/ci.yml
  buf.gen.e2e.yaml
  buf.gen.yaml
  buf.work.yaml
  package.json
  pnpm-lock.yaml
  scripts/compile-extensions-proto
  scripts/compile-testapis-proto
  scripts/protocw
Labels: build :building_construction:

#299 build: fix e2e test generator scripts
  e2e/tests/nexus--deprecation--google-protobuf/package.json
  e2e/tests/nexus--deprecation--protobufjs/package.json
  e2e/tests/nexus--edgecases-import_from_same_pkg--google-protobuf/package.json
  e2e/tests/nexus--edgecases-import_from_same_pkg--protobufjs/package.json
  e2e/tests/nexus--edgecases-import_squashed_union--google-protobuf/package.json
  e2e/tests/nexus--edgecases-import_squashed_union--protobufjs/package.json
  e2e/tests/nexus--empty_types--google-protobuf/package.json
  e2e/tests/nexus--empty_types--protobufjs/package.json
  e2e/tests/nexus--enums--google-protobuf/package.json
  e2e/tests/nexus--enums--protobufjs/package.json
  e2e/tests/nexus--extensions--google-protobuf/package.json
  e2e/tests/nexus--extensions--protobufjs/package.json
  e2e/tests/nexus--field_behavior--google-protobuf/package.json
  e2e/tests/nexus--field_behavior--protobufjs/package.json
  e2e/tests/nexus--multipkgs--google-protobuf/package.json
  e2e/tests/nexus--multipkgs--protobufjs/package.json
  e2e/tests/nexus--nested--google-protobuf/package.json
  e2e/tests/nexus--nested--protobufjs/package.json
  e2e/tests/nexus--oneof--google-protobuf/package.json
  e2e/tests/nexus--oneof--protobufjs/package.json
  e2e/tests/nexus--primitives--google-protobuf/package.json
  e2e/tests/nexus--primitives--protobufjs/package.json
  e2e/tests/nexus--proto3_optional--google-protobuf/package.json
  e2e/tests/nexus--proto3_optional--protobufjs/package.json
  e2e/tests/nexus--wktypes--google-protobuf/package.json
  e2e/tests/nexus--wktypes--protobufjs/package.json
  e2e/tests/pothos--deprecation--ts-proto/package.json
  e2e/tests/pothos--edgecases-import_from_same_pkg--ts-proto/package.json
  e2e/tests/pothos--edgecases-import_squashed_union--ts-proto/package.json
  e2e/tests/pothos--empty_types--ts-proto/package.json
  e2e/tests/pothos--enums--ts-proto/package.json
  e2e/tests/pothos--extensions--ts-proto/package.json
  e2e/tests/pothos--field_behavior--ts-proto/package.json
  e2e/tests/pothos--multipkgs--ts-proto/package.json
  e2e/tests/pothos--nested--ts-proto/package.json
  e2e/tests/pothos--oneof--ts-proto/package.json
  e2e/tests/pothos--primitives--ts-proto-with-forcelong-number/package.json
  e2e/tests/pothos--primitives--ts-proto/package.json
  e2e/tests/pothos--proto3_optional--ts-proto/package.json
  e2e/tests/pothos--wktypes--ts-proto-with-forcelong-number/package.json
  e2e/tests/pothos--wktypes--ts-proto/package.json
  scripts/setupE2ETests.ts
  scripts/workspacePackageConfig.ts
Labels: build :building_construction:

#302 ci: run build explicitly before publish
  .github/workflows/release.yml
  package.json
Labels: build :building_construction:

#303 ci: create snapshot release when main branch is updated
  .github/workflows/release.yml
Labels: build :building_construction:

#304 build: add `pnpm build` script
  package.json
Labels: build :building_construction:

#305 ci: fix release scripts
  .github/workflows/release.yml
  package.json
Labels: build :building_construction:

#306 ci: fix release scripts again
  .github/workflows/release.yml
  package.json
Labels: build :building_construction:
